name: firecraft
description: A simplified and intuitive wrapper for Cloud Firestore operations in Flutter applications.
version: 0.1.1
repository: https://github.com/sinan-aktepe/firecraft
homepage: https://github.com/sinan-aktepe/firecraft
topics: [firestore, firebase]

environment:
  sdk: ^3.5.0
  flutter: '>=3.24.0'

dependencies:
  cloud_firestore: ^5.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
